permalink: /:title.html
description: "Aeolus is software for running virtual machines both internally on your own equipment, and in Clouds from several leading vendors. All at the same time."
keywords: "Ruby, Java, Cloud computing, Deltacloud, Rails, RoR, Sinatra, Javascript, Python"
title: The Aeolus Project
tagline: Manage Your Cloud Deployments with Ease
author: The Aeolus Project Content Writers
host: www.aeolusproject.org
production_url: http://www.aeolusproject.org
exclude: README.md, image_source
